version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1884:1884"
    volumes:
      - ./mosquitto/:/mosquitto/config
    networks:
      - mosquitto

  metrics-server-mqtt:
    build:
      context: .
      dockerfile: mqtt.Dockerfile
    ports:
      - "8081:8081"
    networks:
      - mosquitto
    depends_on:
      - mosquitto
    cap_add:
      - NET_ADMIN

  metrics-server-mqtt-udp:
    build:
      context: .
      dockerfile: mqtt-udp.Dockerfile
    ports:
      - "8082:8082"
      - "1883:1883/udp"
    cap_add:
      - NET_ADMIN
    networks:
      - mosquitto

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - mosquitto

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - mosquitto

networks:
  mosquitto:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
