services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1884:1884"
    volumes:
      - ./mosquitto/:/mosquitto/config
    networks:
      - mosquitto
    cap_add:
      - NET_ADMIN

  metrics-server-mqtt:
    build:
      context: .
      dockerfile: mqtt.Dockerfile
    ports:
      - "8081:8081"
    networks:
      - mosquitto
    depends_on:
      - mosquitto
    cap_add:
      - NET_ADMIN

  metrics-server-mqtt-udp:
    build:
      context: .
      dockerfile: mqtt-udp.Dockerfile
    ports:
      - "8082:8082"
      - "1883:1883/udp"
    cap_add:
      - NET_ADMIN
    networks:
      - mosquitto

#  metrics-server-mqtt-quic:
#    build:
#      context: .
#      dockerfile: quic.Dockerfile
#    ports:
#      - "8083:8083"
#      - "1885:1885/udp"
#    cap_add:
#      - NET_ADMIN
#    networks:
#      - mosquitto

  clickhouse:
    image: clickhouse/clickhouse-server:25.8
    container_name: clickhouse
    mem_limit: 2g
    memswap_limit: 2g
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse_data:/var/lib/clickhouse
      - ./clickhouse_config/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse_config/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./clickhouse_init:/docker-entrypoint-initdb.d
    networks:
      - mosquitto

networks:
  mosquitto:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
