plugins {
    id 'java-library'
}

group = 'com.manilov.common'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = '21'
}

dependencies {
    api 'org.springframework.boot:spring-boot-starter:3.5.5'
    api 'org.springframework.boot:spring-boot-starter-jdbc:3.5.5'
    api 'com.clickhouse:jdbc-v2:0.9.2'
    api 'org.lz4:lz4-java:1.8.0'
    api 'io.netty:netty-all:4.1.121.Final'
    implementation 'io.netty.incubator:netty-incubator-codec-classes-quic:0.0.72.Final'
    runtimeOnly 'io.netty.incubator:netty-incubator-codec-native-quic:0.0.72.Final:linux-x86_64'
    runtimeOnly 'io.netty.incubator:netty-incubator-codec-native-quic:0.0.72.Final:linux-aarch_64'
    runtimeOnly 'io.netty.incubator:netty-incubator-codec-native-quic:0.0.72.Final:osx-x86_64'
    runtimeOnly 'io.netty.incubator:netty-incubator-codec-native-quic:0.0.72.Final:osx-aarch_64'
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

}
